optimizer:
  name: Adam
  lr: 3e-4
  weight_decay: 0
  betas:
    - 0.9
    - 0.999
  eps: 1e-8

network:
  name: double_q_net
  hidden_dim: 256
  init: xavier_normal
  activation: relu
  use_target_network: True
  use_qv_net: True
  tau: 0.005
  target_update_interval: 1
